---
kind: pipeline
type: docker
name: hello-world
steps:
#  - name: docker
#  image: plugins/docker
#  settings:
#    repo:<dockerhub_username>/docker-hello-world
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#    tags:
#      - latest

  - name: testing
    image: maven/3.8.7-eclipse-temurin-17-focal
    commands:
      - mvn test

  - name: build & deploy
    image: maven/maven:3.8.7-eclipse-temurin-17-focal
    commands:
      - mvn compile jib:build
    when:
      branch: master
