---
kind: pipeline
type: docker
name: hello-world
steps:
#  - name: docker
#  image: plugins/docker
#  settings:
#    repo:<dockerhub_username>/docker-hello-world
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#    tags:
#      - latest

  - name: testing
    image: maven:3-sapmachine-17
    commands:
      - mvn test

  - name: build
    image: maven:3-sapmachine-17
    commands:
      - mvn compile

#  - name: publish
#    image: trion/jib-cli
#    commands:
#      - jib build --build-file=jib/jib.yaml --target=registry.hub.docker.com/930c/cinetastisch-backend:${DRONE_COMMIT_SHA:0:7}
#    volumes:
#      - name: cache
#        path: /tmp/.cache/google-cloud-tools-java/

  - name: deploy
    image: maven:3-sapmachine-17
    commands:
      - mvn compile jib:build